### ISSUE TITLE
BIG_TABLE_BY_SIZE  、BIG_SCHEMA_BY_TABLE_NUM规则有问题

### ISSUE THREAD

**Issue by himura-kenshin** [CreditEaseDBA/Themis#10]
BIG_TABLE_BY_SIZE
配置的10G  ，为什么显示 0GB  会违反规则 

BIG_SCHEMA_BY_TABLE_NUM配置的5000   我的只有22个就违反规则

而且这两个在mongo里面 的参数名字都是  table_size

**Comment by tuteng** [comment]
https://github.com/CreditEaseDBA/Themis/issues/2
