### ISSUE TITLE
关于settings.py中的mysql设置问题

### ISSUE THREAD

**Issue by woson** [CreditEaseDBA/Themis#14]
# pt-query save data for mysql account, password
PT_QUERY_USER = "user"
PT_QUERY_PORT = 3306
PT_QUERY_SERVER = "127.0.0.1"
PT_QUERY_PASSWD = "password"
PT_QUERY_DB = "slow_query_log"    
中的 slow_query_log 库是只需要读权限吗? 还是必须要有dml的权限?

**Comment by tuteng** [comment]
平台只需要查询的权限，
但是 pt-query-digest 在搜集慢查询的时候，需要往里边插入数据，会需要dml权限
