### ISSUE TITLE
任务执行完成之后，导出的报告打开都是乱码

### ISSUE THREAD

**Issue by dikang123** [CreditEaseDBA/Themis#4]
使用的chrome版本：57.0.2987.110 (64-bit)
新版本的chrome没有编码选项。

使用其他浏览器（比如IE浏览器）报告的内容加载不起来。

**Comment by tuteng** [comment]
我的版本 58.0.3029.81 (64-bit) 没有遇到这个问题
新版本chrome确实没有了设置编码选项，可以借助chrome的插件实现

由于最后生成的报告比较大，使用其他浏览器确实加载很慢，因此还是建议使用chrome，如果不打算将报告发送给其他人，可以直接在平台查看

**Comment by himura-kenshin** [comment]
能否导出EXECLE 或者PDF

**Comment by tuteng** [comment]
最后生成的报告为离线的html格式
