### ISSUE TITLE
违反规则column_wrong_type时，报告存在重复输出

### ISSUE THREAD

**Issue by dikang123** [CreditEaseDBA/Themis#5]
![image](https://cloud.githubusercontent.com/assets/16694535/25612846/c16b296a-2f5e-11e7-9873-76a5b19b3e08.png)

同一张表的同一个字段，输出了8次

**Comment by tuteng** [comment]
https://github.com/CreditEaseDBA/Themis/commit/04ed220cbd11655f002aadd90a9244a0f260b5e2
可以参考这个修改源代码，或者拉取新的代码重新部署

**Comment by dikang123** [comment]
嗯，修改后，解决了 @tuteng
