### ISSUE TITLE
任务发布页面，选择“text"规则类型，无法展示”text"相关的规则

### ISSUE THREAD

**Issue by dikang123** [CreditEaseDBA/Themis#6]
![image](https://cloud.githubusercontent.com/assets/16694535/25688940/ef38a266-30b5-11e7-8df2-a1379c75c9e2.png)
如上图，选择了“text"规则类型做分析，但是页面下方展示出来的并不是”text"的各条规则。

**Comment by tuteng** [comment]
刷新一下，重新再点击，或者打开调试工具观察一下网络，我感觉应该是某些请求没有响应，你看到的是上一次的请求

**Comment by dikang123** [comment]
额，确实是上一次的请求，但是如果只点击text按钮，页面下方并没有办法展示text相关的规则。

**Comment by himura-kenshin** [comment]
![image](https://cloud.githubusercontent.com/assets/24806747/25734243/939fa2c2-3193-11e7-9b1f-c7e28c522c3c.png)

**Comment by dikang123** [comment]
@tuteng 
代码：
https://github.com/CreditEaseDBA/Themis/blob/dev/webui/view.py#L262
https://github.com/CreditEaseDBA/Themis/blob/dev/webui/wtform_models.py#L75
这两处对text规则的描述，一个是“SQLTEXT",一个是”TEXT"，我把“SQLTEXT"统一改成”TEXT“试了下，页面可以正常展示了：
![image](https://cloud.githubusercontent.com/assets/16694535/25734694/1cc70af0-3198-11e7-8aa5-9388004bb669.png)
![image](https://cloud.githubusercontent.com/assets/16694535/25734706/50ba0042-3198-11e7-92cf-43cfbb21283d.png)
