### ISSUE TITLE
发布对象任务报错     --字段类型的问题

### ISSUE THREAD

**Issue by himura-kenshin** [CreditEaseDBA/Themis#9]
![image](https://cloud.githubusercontent.com/assets/24806747/25886336/be819004-358f-11e7-80ef-a5c359e8ce22.png)
另外好像支持的类型不全   不支持地理位置类型等

**Comment by tuteng** [comment]
https://github.com/CreditEaseDBA/Themis/blob/master/rule_analysis/rule/obj/table_record_length.py 参考这里的类型

**Comment by himura-kenshin** [comment]
嗯  截图中的报错是什么意思，这个类型不是支持吗  Decimal

**Comment by tuteng** [comment]
https://github.com/CreditEaseDBA/Themis/commit/d3fdb7a7150f7e9c9eb45fce13d6585174c7cd5c
用这个试试

**Comment by himura-kenshin** [comment]
不好意思这个好像没有用
